### ISSUE TITLE
Support Node.js v4

### ISSUE THREAD

**Issue by 0x6b** [textlint-rule/textlint-rule-no-dead-link#100]
textlint supports Node.js 4.0.0+ as described at the [README](https://github.com/textlint/textlint) so I wonder if this rule could support v4 as well.

Since authors explicitly support Node 6+ at commit e298199f9748df00d4512895ec973911a406d801, I'm not sure it could be feasible but I created a fork at https://github.com/0x6b/textlint-rule-no-dead-link/tree/support-node4 and ready to open a pull request. Could you let me know your thoughts. Thank you.

```diff
diff --git a/.babelrc b/.babelrc
index 273a666..ca83ad4 100644
--- a/.babelrc
+++ b/.babelrc
@@ -4,8 +4,9 @@
       "env",
       {
         "targets": {
-          "node": 6
-        }
+          "node": 4
+        },
+        "exclude": ["babel-plugin-transform-regenerator"]
       }
     ]
   ]
```

**Comment by nodaguti** [comment]
Thanks for the suggestion!
After some googling, I've realised that Node 4.x is an active LTS until April 2017, so I'm 100% OK to support Node v4.
Your PR is highly welcomed!

**Comment by 0x6b** [comment]
@nodaguti, thank you! I'm working on Travis CI. I will open a pull request after confirming successful build on my end.

**Comment by 0x6b** [comment]
Opened #101. Since Travis CI job queue have been stuffed recently, the test might be timed out. (I had to run twice.)
