### ISSUE TITLE
Don't check reference-style links

### ISSUE THREAD

**Issue by gregurco** [textlint-rule/textlint-rule-no-dead-link#105]
Hello.
This rule is not validating links in reference-style. For example:

```
(some link text)[1]

[1]: https://foo.bar
```

Plugin is simply ignore it, but error expected.

**Comment by azu** [comment]
Thanks for report.

> This rule is not validating links in reference-style.

Yes. Currently this rule does not support it.

Probably, we can surppot reference-style by following imeplemtation.
(I did not test the code)


```
// https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/3984344d642e0323903d6d34326d02f6a33be269/src/no-dead-link.js#L223
    ["Definition"](node) {
      if (typeof node.url === 'undefined') {
        return;
      }

      // [1]: http://example.com
      //      ^
      const index = node.raw.indexOf(node.url) || 0;

      URIs.push({
        node,
        uri: node.url,
        index,
      });
   },
```

📝 Note: `Definition` Node type is markdown specific.
(It is not a parts of [TxtAST](https://textlint.github.io/docs/txtnode.html))

![image](https://user-images.githubusercontent.com/19714/43204717-99051f16-905c-11e8-9ea4-78bde219dde5.png)

- https://textlint.github.io/astexplorer/
