### ISSUE TITLE
When fixing URLs with hashes, hashes are removed

### ISSUE THREAD

**Issue by lilaconlee** [textlint-rule/textlint-rule-no-dead-link#107]
Running `textlint --fix` on

```
http://mochajs.org/#bdd 
```

Results in:

```
https://mochajs.org/
```

**Comment by 0x6b** [comment]
@azu, could you kindly review my preliminary implementation for preserving hash component?

P.S. I'm slowly rebuilding my life after health issue. Sorry for long absence from contribution!

**Comment by azu** [comment]
@lilaconlee https://github.com/textlint-rule/textlint-rule-no-dead-link/releases/tag/4.4.1 preserve hash by default.
Please try it.

**Comment by lilaconlee** [comment]
Works great!
