### ISSUE TITLE
Ignore mailto: links by default

### ISSUE THREAD

**Issue by parthpp** [textlint-rule/textlint-rule-no-dead-link#112]
@azu 
This rule currently tries to validate `mailto:` links. This does not make sense, since it cannot be validated without sending an email. The rule uses [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch) which internally calls [`node-fetch`](https://github.com/bitinn/node-fetch) and node-fetch [only validates https links](https://github.com/bitinn/node-fetch/blob/bf8b4e8db350ec76dbb9236620f774fcc21b8c12/src/request.js#L196-L198). Thus this rule should ignore `mailto:` links by default. The current work around available is to add this to rule config in `.textlintrc` 
```json
{
 "rules":{ 
    "no-dead-link": {
      "ignore":["mailto:*@*.*"]
     }
  }
}

```

**Comment by amimas** [comment]
I think this rule should ignore non http protocols out of the box such as, mailto, ftp, sftp, scp, etc.

**Comment by azu** [comment]
Agree.
This rule should check only `/^https?:/` link by default.

**Comment by azu** [comment]
Put /^https?/ validation before https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/3f9508c2de463c99ac257b9e68b7d20e75e3d8dc/src/no-dead-link.js#L148 and resolve this issue.

And, we need to add some test case to valid case

https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/3f9508c2de463c99ac257b9e68b7d20e75e3d8dc/test/no-dead-link.js#L10-L98

```js
	if (!/^https?:$/.test(uri)) {
		return
    }
    if (isIgnored(uri, opts.ignore)) {
      return;
    }
```

Welcome to Pull Request!

**Comment by azu** [comment]
Fixed in https://github.com/textlint-rule/textlint-rule-no-dead-link/releases/tag/4.4.2
