### ISSUE TITLE
`socket hang up` error for a lot of links

### ISSUE THREAD

**Issue by amimas** [textlint-rule/textlint-rule-no-dead-link#120]
I have a documentation repository containing close to 250 markdown files. The rule is working well so far. I am creating a new version of the docs by duplicating all of those markdown files under a separate directory.

When I duplicate those files and try to run the linter rule on all of them (close to 500 files), on my local machine it runs fine. But, on my CI server the linter rule is failing to validate external links. All of the errors are due to `socket hang up`. For example:

```log
  52:19  error  http://schemaspy.sourceforge.net/ is dead. (request to http://schemaspy.sourceforge.net/ failed, reason: socket hang up)  no-dead-link
   7:62   error    https://junit.org/junit5/ is dead. (request to https://junit.org/junit5/ failed, reason: Client network socket disconnected before secure TLS connection was established)  no-dead-link
  22:204  error    http://en.wikipedia.org/wiki/Component_model is dead. (request to http://en.wikipedia.org/wiki/Component_model failed, reason: socket hang up)  no-dead-link
  91:151  error  https://www.ietf.org/rfc/rfc2426.txt is dead. (request to https://www.ietf.org/rfc/rfc2426.txt failed, reason: socket hang up)  no-dead-link
  72:279  error    http://jquery.com/ is dead. (request to http://jquery.com/ failed, reason: socket hang up)    no-dead-link
```

These errors are appearing in the CI server consistently but if I don't have the files duplicated, I don't seem to have this issue.

Is there a limitation or performance issue because of the large amount of files/contents?

```

**Comment by azu** [comment]
Interesting.

Currently, linting(fetching) in parallel.
https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/a6dd6c287258eb2325548b1aeb7b282049c6b9de/src/no-dead-link.js#L272
Probably, we need to limit the concurrency for avoiding socket hangup.

- [sindresorhus/p-all: Run promise-returning & async functions concurrently with optional limited concurrency](https://github.com/sindresorhus/p-all)

Also, we need to add cache mechanism to reduce feting cost.

**Comment by amimas** [comment]
This became a major blocking issue for me. As a work-around, I created separate command in my `package.json` that can be called and validate different versions of docs separately.

As for this issue, caching mechanism is definitely needed. I'm also wondering if concurrency needs to be a configurable option with a sensible default out of the box.

**Comment by azu** [comment]
#122 I've implemented memorize and concurrency throttling(default: 8).
I think that it will resolve this issue. 

Please try `textlint-rule-no-dead-link@4.4.4`.

**Comment by amimas** [comment]
Thanks @azu 

I'll try it out soon.
