### ISSUE TITLE
`ignore` configuration is working inconsistently

### ISSUE THREAD

**Issue by parkas2018** [textlint-rule/textlint-rule-no-dead-link#124]
Hello,

I have an "internal" link that I specifically didn't want to validate. So, I had added that URL to the `ignore` array of this rule's configuration. Lately I'm seeing an odd behaviour where this URL is being reported as broken/dead link.

After some debugging, I noticed that URL has been inconsistent in terms of what response status is being returned. For example, sometimes it returns `403 (Forbidden)` or `reason: connect ETIMEDOUT`

How does this rule handle the list of URLs that are added into the `ignore` array? Does it completely ignore those from being checked/validated? That's what I understood from this rule's docs/readme, but it seems to be working differently.

I'm currently using version `4.4.3` of this rule.

**Comment by azu** [comment]
Fmm, `ignore` option use [minimatch](https://www.npmjs.com/package/minimatch).

https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/f8eec2df298446247a0fcb75ba187873d359463e/src/no-dead-link.js#L74-L76

Please tell me, your config and url example.

**Comment by parkas2018** [comment]
Haven't been able to re-produce this again. Closing it for now.
