### ISSUE TITLE
Certain web servers return "403 Forbidden" status code instead of "200 OK" due to User-Agent value

### ISSUE THREAD

**Issue by amimas** [textlint-rule/textlint-rule-no-dead-link#128]
## Problem

I'm currently using the latest version (`4.6.2`) and this rule is failing to validate the following link:

https://issues.jenkins-ci.org/browse/JENKINS-59261

Textlint receives a `403 Forbidden` status code when it tries to validate and so it produces following error message:

```log
  41:64  error  https://issues.jenkins-ci.org/browse/JENKINS-59261 is dead. (403 Forbidden)  no-dead-link
```

Right now, the `User-Agent` value is set to be `textlint-rule-no-dead-link/1.0` whenever the rule tries to validate a link:

https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/ee04a13d916462b3b0dc4899d9c981c437ef3851/src/no-dead-link.js#L123

I tried with different values using `curl` on my machine to validate the above link. For example:

```bash
$ curl -I -H "host: issues.jenkins-ci.org" -H "User-Agent: check link" -H "Accept: */*" https://issues.jenkins-ci.org/browse/JENKINS-59261
$ curl -I -H "host: issues.jenkins-ci.org" -H "User-Agent: blah" -H "Accept: */*" https://issues.jenkins-ci.org/browse/JENKINS-59261 
$ curl -I -H "host: issues.jenkins-ci.org" -H "User-Agent: textlint/1.0 (rule: no-dead)" -H "Accept: */*" https://issues.jenkins-ci.org/browse/JENKINS-59261
$ curl -I -H "host: issues.jenkins-ci.org" -H "User-Agent: textlint/1.0 (rule: no-dead-link)" -H "Accept: */*" https://issues.jenkins-ci.org/browse/JENKINS-59261
```

In my observation, it seems the server is returning `403` status code whenever the `User-Agent` value of the header contains the word "link".

```log
HTTP/2 403 
date: Thu, 12 Dec 2019 20:46:24 GMT
server: Apache/2.4.29 (Ubuntu)
access-control-allow-origin: http://localhost:8000
content-type: text/html; charset=iso-8859-1
```

I noticed that particular site is running on Apache 2.4.29. I'm not sure if this is a bug or intentional for the Apache server to deny access based on the user agent value, or if the the problem is somewhere else on that site.

## Suggestion

I understand this issue "technically" may not be a bug for this textlint rule. However, the purpose of this rule is to validate external links in various text based files so that readers of those files don't get any dead links.

From an end users perspective, they will try to access links in those text based files using a web browser. So, would it be better to use a `User-Agent` value used by an established web browser? I'm not sure which browser's value should be used. I think I'll leave it to you to decide.

We could open this as a bug with Apache. I've looked into it and there's a lot of work involved in opening bug report with them (http://httpd.apache.org/bug_report.html). The problem is that, even if it gets accepted as a bug and is fixed, not everyone out there will upgrade right away. That means, this textlint rule will continue to fail to validate links from any servers that are affected with this issue.

Maybe there's a different cause to this problem, which is much easier to solve 😄

**Comment by azu** [comment]
#133 implemnet `userAgent` options.
