### ISSUE TITLE
Error: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by amimas** [textlint-rule/textlint-rule-no-dead-link#129]
Textlint and this rule version used in my project:

```json
{
    "devDependencies": {
        "textlint": "^11.6.1",
        "textlint-rule-no-dead-link": "^4.6.2",
}
```

Textlint configuration:

```json
{
  "rules": {
    "no-dead-link": {
      "checkRelative": false,
      "ignore": [],
      "ignoreRedirects": true
    }
  }
}
```

When running textlint with the above rule and configuration to scan markdown files in a directory, I'm getting the error `Cannot read property 'loc' of undefined`

```sh
$ textlint --config .textlint-config-no-dead-link.json '../docs/dev/guides/*.md'

✖ Error
Cannot read property 'loc' of undefined

✖ Stack trace
TypeError: Cannot read property 'loc' of undefined
    at validate (/my-docs-site/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/context/TextlintSourceCodeImpl.js:24:14)
    at new TextlintSourceCodeImpl (/my-docs-site/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/context/TextlintSourceCodeImpl.js:43:9)
    at TextlintKernel._parallelProcess (/my-docs-site/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/textlint-kernel.js:139:26)
    at /my-docs-site/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/textlint-kernel.js:86:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

From the error message, it's not clear what is the root cause but I was able to narrow it down to the lines by trial and error. It seems the markdown files I'm passing to textlint, had "tab" character for indentation instead of space. For example, consider the following text snippet:

```markdown
* Below are the two types of parameters expected:

    * Type `String` called `code`
    * Type `boolean` called `accepted`
```

In the above snippet, I have a nested list. The nested list originally had used "tab" character for indentation. Once I removed the tab and replaced with "space" (also configured my vs code editor to use 4 spaces for tab/indentation), textlint was able to run this rule successfully.

I'm not yet sure if this is an issue with this particular rule or an issue with textlint kernel.

**Comment by amimas** [comment]
I tried using other textlint rules that seem to be running into same issue. So, I think this issue is not specific to this particular rule. It might be an issue in the textlint itself or one of it's dependencies (i.e. textlint kernel).

@azu - Are you able to move this issue to the textlint project below or any other projects that this issue belongs to?

https://github.com/textlint/textlint

**Comment by azu** [comment]
Fmm. its strange.
Maybe, textlint's bug.

This error is occurred before linting with the rule(no-dead).

**Comment by azu** [comment]
I've created an issue https://github.com/textlint/textlint/issues/661

**Comment by azu** [comment]
This issue is fixed in https://github.com/textlint/textlint/releases/tag/textlint%4011.6.3

Thanks for report!
