### ISSUE TITLE
Request for transfer: textlint-rule

### ISSUE THREAD

**Issue by azu** [textlint-rule/textlint-rule-no-dead-link#92]
Hi @nodaguti, I've created new organization [textlint-rule](https://github.com/textlint-rule "textlint-rule") to help users to find related rules easily, and I want you to transfer this project to [textlint-rule](https://github.com/textlint-rule "textlint-rule") org.

I've sent invitation of GitHub's [textlint-rule](https://github.com/textlint-rule "textlint-rule")  org and npm's [@textlint-rule](https://www.npmjs.com/org/textlint-rule "@textlint-rule") team. 

For more details, see maintenance policy guide.

- [textlint-rule/organization: Maintenance Guidelines for textlint-rule organization](https://github.com/textlint-rule/organization#for-new-member "textlint-rule/organization: Maintenance Guidelines for textlint-rule organization")

If you agree with this, please [transfer](https://help.github.com/articles/about-repository-transfers/ "transfer") this repository and add npm pacakge access to `textlint-rule:developers` team.

If you do not agree with this, it's no problem at all :)

Thanks!

**Comment by azu** [comment]
@nodaguti  How do you think?

**Comment by azu** [comment]
📝 Minimal Steps on browser

1. Go to https://github.com/nodaguti/textlint-rule-no-dead-link/settings
2. Transfer this repository to `textlint-rule`
3. Go to https://github.com/textlint-rule/organization
4. Select `textlint-rule-no-dead-link` from "Populate from personal packages "

**Comment by nodaguti** [comment]
Thank you for the invitation!
I'm going to transfer the repository and grant the access permission.

**Comment by nodaguti** [comment]
During the transfer, an error saying `textlint-rule already has a repository in the nodaguti/textlint-rule-no-dead-link network` has shown up 🤔 
Possibly that's down to the forked version of `no-dead-link` (See [here](https://help.github.com/articles/about-repository-transfers/)).

I'm sorry as it's mainly because I've been away from Github these days.

**Comment by azu** [comment]
@nodaguti Fmm, It is strange.
I've deletede https://github.com/textlint-rule/textlint-rule-no-dead-link-fork
Can you transfer again?

**Comment by azu** [comment]
Thanks for transfer!

FYI: I've re-push https://github.com/textlint-rule/textlint-rule-no-dead-link-fork and archived it.

**Comment by nodaguti** [comment]
I've retried again and succeeded to transfer the package!
Thanks for your help.
