### ISSUE TITLE
Support local link

### ISSUE THREAD

**Issue by azu** [textlint-rule/textlint-rule-no-dead-link#94]
I've added local link feature into fork version.

https://github.com/textlint-rule/textlint-rule-no-dead-link-fork/commit/f0063e9f7e0ffea5c5d10afd8cf55afdce12f48f

`a.md`:
```
[b](b.md) <= Check existing of b.md 
```

It is useful for some documentation tools like [GitBook](https://www.gitbook.com/) and  [Docusaurus](https://docusaurus.io/ "Docusaurus · Easy to Maintain Open Source Documentation Websites").

Currently, if turn on `checkRelative`, the user should specify `baseURI`.
In my experimental implementaion, if turn on only `checkRelative`, check the file path as local link.

**Comment by nodaguti** [comment]
Sounds great!
I'm going to work on this :)

**Comment by nodaguti** [comment]
I'm not sure if it does actually work fine or not but I've pushed https://github.com/textlint-rule/textlint-rule-no-dead-link/commit/a4b11d2928f0df0a1bf8325dafa4c6947d61e9bf.
I should write some tests after `textlint-tester` support `inputPath` option.

**Comment by azu** [comment]
Closed by #95 and  a4b11d2
