### ISSUE TITLE
Local path resolution failure on Windows platform

### ISSUE THREAD

**Issue by 0x6b** [textlint-rule/textlint-rule-no-dead-link#97]
When the rule find local file path, it will try to resolve relative uri to a file by [URI.resolve](https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/master/src/no-dead-link.js#L149). On Windows platform, `protocol` property will be drive letter and it causes unexpected fetch call then `node-fetch` throws [`only absolute urls are supported`](https://github.com/bitinn/node-fetch/blob/v1.6.3/index.js#L54) error.

I'm sorry but it is difficult for me to reproduce/fix this issue locally as I have no Windows environment. Please refer to https://github.com/textlint/textlint/pull/442#issuecomment-354599661 for detail.

**Comment by azu** [comment]
I've fixed it #99 and released https://github.com/textlint-rule/textlint-rule-no-dead-link/releases/tag/4.1.2

/cc @nodaguti
